project          = "learn-kube-hard-way-dmazin"
credentials_file = "~/.google/learn-kube-hard-way-dmazin/editor-sa-private-key.json"
region           = "us-west4"
zone             = "us-west4-a"
network_name = "kubernetes-the-hard-way"